version: '3.1'
services:
  # Backend service
  backend:
    build: ./backend
    ports:
      - "1337:1337"
    depends_on:
      - shard1-primary
      - shard2-secondary
      - redis
    networks:
      - musicapp-network
  
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - musicapp-network

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - musicapp-network

  # Config Server
  configsvr:
    image: mongo:8.0.1-noble
    container_name: configsvr_container
    command: mongod --configsvr --replSet configReplSet --port 27017
    # ports:
    #   - "27017:27017"
    links:
      - shard1-primary
      - shard2-secondary
    networks:
      - musicapp-network

  # Shard 1 - Primary
  shard1-primary:
    image: mongo:8.0.1-noble
    container_name: shard1-primary_container
    command: mongod --shardsvr --replSet shard1 --port 27017
    # ports:
    #   - "27018:27017"
    networks:
      - musicapp-network

  # Shard 2 - Secondary
  shard2-secondary:
    image: mongo:8.0.1-noble
    container_name: shard2-secondary_container
    command: mongod --shardsvr --replSet shard2 --port 27017
    # ports:
    #   - "27019:27017"
    networks:
      - musicapp-network

  # Mongos Router
  mongos:
    image: mongo:8.0.1-noble
    container_name: mongos_container
    depends_on:
      - configsvr
      - shard1-primary
      - shard2-secondary
    command: mongos --configdb configReplSet/configsvr:27017 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - musicapp-network

volumes:
  shard1-primary:
  shard2-secondary:

networks:
  musicapp-network:
    driver: bridge