version: '3.8'
services:
  # Backend service
  backend:
    image: huyphanluong/music-app-backend:latest
    ports:
      - "1337:1337"
    environment:
      - MONGO_URI=mongodb://mongo:27017/music_streaming
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyOTA5MDMwOCwiaWF0IjoxNzI5MDkwMzA4fQ.rupFvTyZwxI_oeZydy3gmxJv9SPiik9-PqjZQwze1mY
    networks:
      - musicapp-network

  # Redis service
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - musicapp-network
    deploy:
      restart_policy:
        condition: on-failure

  # Frontend service
  frontend:
    image: huyphanluong/music-app-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - musicapp-network
    depends_on:
      - backend

  # MongoDB service
  mongo:
    image: mongo:8.0.1-noble
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=music_streaming
    networks:
      - musicapp-network
    volumes:
      - mongo_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

volumes:
  mongo_data:

networks:
  musicapp-network:
    driver: overlay