services:
  frontend:
    # image: phuongtoan/music-app-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - backend

  backend:
    # image: phuongtoan/music-app-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 1337:1337
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: phuongtoan/music-app-mongodb:latest
    # image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge